#!/bin/bash
#DEBHELPER#
set -e
case $1 in
  *)
    if [ -d /home/osmc/.kodi/userdata/addon_data/script.moonlight-osmc ]; then
      rm -rf /home/osmc/.kodi/userdata/addon_data/script.moonlight-osmc
    fi
  ;;
esac
